// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reimbursement "payslip-generation-system/internal/entity/reimbursement"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockReimbursementRepositoryProvider is a mock of ReimbursementRepositoryProvider interface.
type MockReimbursementRepositoryProvider struct {
	ctrl     *gomock.Controller
	recorder *MockReimbursementRepositoryProviderMockRecorder
}

// MockReimbursementRepositoryProviderMockRecorder is the mock recorder for MockReimbursementRepositoryProvider.
type MockReimbursementRepositoryProviderMockRecorder struct {
	mock *MockReimbursementRepositoryProvider
}

// NewMockReimbursementRepositoryProvider creates a new mock instance.
func NewMockReimbursementRepositoryProvider(ctrl *gomock.Controller) *MockReimbursementRepositoryProvider {
	mock := &MockReimbursementRepositoryProvider{ctrl: ctrl}
	mock.recorder = &MockReimbursementRepositoryProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReimbursementRepositoryProvider) EXPECT() *MockReimbursementRepositoryProviderMockRecorder {
	return m.recorder
}

// InsertReimbursement mocks base method.
func (m *MockReimbursementRepositoryProvider) InsertReimbursement(ctx context.Context, rmb reimbursement.Reimbursement) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertReimbursement", ctx, rmb)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertReimbursement indicates an expected call of InsertReimbursement.
func (mr *MockReimbursementRepositoryProviderMockRecorder) InsertReimbursement(ctx, rmb interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertReimbursement", reflect.TypeOf((*MockReimbursementRepositoryProvider)(nil).InsertReimbursement), ctx, rmb)
}
