// Code generated by MockGen. DO NOT EDIT.
// Source: repository_db.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reimbursement "payslip-generation-system/internal/entity/reimbursement"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockdbRepoProvider is a mock of dbRepoProvider interface.
type MockdbRepoProvider struct {
	ctrl     *gomock.Controller
	recorder *MockdbRepoProviderMockRecorder
}

// MockdbRepoProviderMockRecorder is the mock recorder for MockdbRepoProvider.
type MockdbRepoProviderMockRecorder struct {
	mock *MockdbRepoProvider
}

// NewMockdbRepoProvider creates a new mock instance.
func NewMockdbRepoProvider(ctrl *gomock.Controller) *MockdbRepoProvider {
	mock := &MockdbRepoProvider{ctrl: ctrl}
	mock.recorder = &MockdbRepoProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockdbRepoProvider) EXPECT() *MockdbRepoProviderMockRecorder {
	return m.recorder
}

// InsertReimbursement mocks base method.
func (m *MockdbRepoProvider) InsertReimbursement(ctx context.Context, rmb reimbursement.Reimbursement) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertReimbursement", ctx, rmb)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertReimbursement indicates an expected call of InsertReimbursement.
func (mr *MockdbRepoProviderMockRecorder) InsertReimbursement(ctx, rmb interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertReimbursement", reflect.TypeOf((*MockdbRepoProvider)(nil).InsertReimbursement), ctx, rmb)
}
