// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	payslip "payslip-generation-system/internal/entity/payslip"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockPayslipRepositoryProvider is a mock of PayslipRepositoryProvider interface.
type MockPayslipRepositoryProvider struct {
	ctrl     *gomock.Controller
	recorder *MockPayslipRepositoryProviderMockRecorder
}

// MockPayslipRepositoryProviderMockRecorder is the mock recorder for MockPayslipRepositoryProvider.
type MockPayslipRepositoryProviderMockRecorder struct {
	mock *MockPayslipRepositoryProvider
}

// NewMockPayslipRepositoryProvider creates a new mock instance.
func NewMockPayslipRepositoryProvider(ctrl *gomock.Controller) *MockPayslipRepositoryProvider {
	mock := &MockPayslipRepositoryProvider{ctrl: ctrl}
	mock.recorder = &MockPayslipRepositoryProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPayslipRepositoryProvider) EXPECT() *MockPayslipRepositoryProviderMockRecorder {
	return m.recorder
}

// BulkInsertPayslips mocks base method.
func (m *MockPayslipRepositoryProvider) BulkInsertPayslips(ctx context.Context, payslips []payslip.Payslip) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkInsertPayslips", ctx, payslips)
	ret0, _ := ret[0].(error)
	return ret0
}

// BulkInsertPayslips indicates an expected call of BulkInsertPayslips.
func (mr *MockPayslipRepositoryProviderMockRecorder) BulkInsertPayslips(ctx, payslips interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkInsertPayslips", reflect.TypeOf((*MockPayslipRepositoryProvider)(nil).BulkInsertPayslips), ctx, payslips)
}

// GetPayslipSummary mocks base method.
func (m *MockPayslipRepositoryProvider) GetPayslipSummary(ctx context.Context, periodID int) (payslip.PayslipSummaryReport, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPayslipSummary", ctx, periodID)
	ret0, _ := ret[0].(payslip.PayslipSummaryReport)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPayslipSummary indicates an expected call of GetPayslipSummary.
func (mr *MockPayslipRepositoryProviderMockRecorder) GetPayslipSummary(ctx, periodID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPayslipSummary", reflect.TypeOf((*MockPayslipRepositoryProvider)(nil).GetPayslipSummary), ctx, periodID)
}

// GetPayslipsByUserID mocks base method.
func (m *MockPayslipRepositoryProvider) GetPayslipsByUserID(ctx context.Context, userID int) ([]payslip.Payslip, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPayslipsByUserID", ctx, userID)
	ret0, _ := ret[0].([]payslip.Payslip)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPayslipsByUserID indicates an expected call of GetPayslipsByUserID.
func (mr *MockPayslipRepositoryProviderMockRecorder) GetPayslipsByUserID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPayslipsByUserID", reflect.TypeOf((*MockPayslipRepositoryProvider)(nil).GetPayslipsByUserID), ctx, userID)
}

// PayslipExistsByPeriodID mocks base method.
func (m *MockPayslipRepositoryProvider) PayslipExistsByPeriodID(ctx context.Context, periodID int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PayslipExistsByPeriodID", ctx, periodID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PayslipExistsByPeriodID indicates an expected call of PayslipExistsByPeriodID.
func (mr *MockPayslipRepositoryProviderMockRecorder) PayslipExistsByPeriodID(ctx, periodID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PayslipExistsByPeriodID", reflect.TypeOf((*MockPayslipRepositoryProvider)(nil).PayslipExistsByPeriodID), ctx, periodID)
}
