// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	audit "payslip-generation-system/internal/entity/audit"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockAuditServiceProvider is a mock of AuditServiceProvider interface.
type MockAuditServiceProvider struct {
	ctrl     *gomock.Controller
	recorder *MockAuditServiceProviderMockRecorder
}

// MockAuditServiceProviderMockRecorder is the mock recorder for MockAuditServiceProvider.
type MockAuditServiceProviderMockRecorder struct {
	mock *MockAuditServiceProvider
}

// NewMockAuditServiceProvider creates a new mock instance.
func NewMockAuditServiceProvider(ctrl *gomock.Controller) *MockAuditServiceProvider {
	mock := &MockAuditServiceProvider{ctrl: ctrl}
	mock.recorder = &MockAuditServiceProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuditServiceProvider) EXPECT() *MockAuditServiceProviderMockRecorder {
	return m.recorder
}

// RecordAuditLog mocks base method.
func (m *MockAuditServiceProvider) RecordAuditLog(ctx context.Context, log audit.AuditLog) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordAuditLog", ctx, log)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RecordAuditLog indicates an expected call of RecordAuditLog.
func (mr *MockAuditServiceProviderMockRecorder) RecordAuditLog(ctx, log interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordAuditLog", reflect.TypeOf((*MockAuditServiceProvider)(nil).RecordAuditLog), ctx, log)
}

// RecordRequestLog mocks base method.
func (m *MockAuditServiceProvider) RecordRequestLog(ctx context.Context, log audit.RequestLog) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordRequestLog", ctx, log)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RecordRequestLog indicates an expected call of RecordRequestLog.
func (mr *MockAuditServiceProviderMockRecorder) RecordRequestLog(ctx, log interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordRequestLog", reflect.TypeOf((*MockAuditServiceProvider)(nil).RecordRequestLog), ctx, log)
}
