// Code generated by MockGen. DO NOT EDIT.
// Source: repository_db.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	audit "payslip-generation-system/internal/entity/audit"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockdbRepoProvider is a mock of dbRepoProvider interface.
type MockdbRepoProvider struct {
	ctrl     *gomock.Controller
	recorder *MockdbRepoProviderMockRecorder
}

// MockdbRepoProviderMockRecorder is the mock recorder for MockdbRepoProvider.
type MockdbRepoProviderMockRecorder struct {
	mock *MockdbRepoProvider
}

// NewMockdbRepoProvider creates a new mock instance.
func NewMockdbRepoProvider(ctrl *gomock.Controller) *MockdbRepoProvider {
	mock := &MockdbRepoProvider{ctrl: ctrl}
	mock.recorder = &MockdbRepoProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockdbRepoProvider) EXPECT() *MockdbRepoProviderMockRecorder {
	return m.recorder
}

// InsertAuditLog mocks base method.
func (m *MockdbRepoProvider) InsertAuditLog(ctx context.Context, log audit.AuditLog) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertAuditLog", ctx, log)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertAuditLog indicates an expected call of InsertAuditLog.
func (mr *MockdbRepoProviderMockRecorder) InsertAuditLog(ctx, log interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertAuditLog", reflect.TypeOf((*MockdbRepoProvider)(nil).InsertAuditLog), ctx, log)
}

// InsertRequestLog mocks base method.
func (m *MockdbRepoProvider) InsertRequestLog(ctx context.Context, log audit.RequestLog) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertRequestLog", ctx, log)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertRequestLog indicates an expected call of InsertRequestLog.
func (mr *MockdbRepoProviderMockRecorder) InsertRequestLog(ctx, log interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertRequestLog", reflect.TypeOf((*MockdbRepoProvider)(nil).InsertRequestLog), ctx, log)
}
