// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	overtime "payslip-generation-system/internal/entity/overtime"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockOvertimeRepositoryProvider is a mock of OvertimeRepositoryProvider interface.
type MockOvertimeRepositoryProvider struct {
	ctrl     *gomock.Controller
	recorder *MockOvertimeRepositoryProviderMockRecorder
}

// MockOvertimeRepositoryProviderMockRecorder is the mock recorder for MockOvertimeRepositoryProvider.
type MockOvertimeRepositoryProviderMockRecorder struct {
	mock *MockOvertimeRepositoryProvider
}

// NewMockOvertimeRepositoryProvider creates a new mock instance.
func NewMockOvertimeRepositoryProvider(ctrl *gomock.Controller) *MockOvertimeRepositoryProvider {
	mock := &MockOvertimeRepositoryProvider{ctrl: ctrl}
	mock.recorder = &MockOvertimeRepositoryProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOvertimeRepositoryProvider) EXPECT() *MockOvertimeRepositoryProviderMockRecorder {
	return m.recorder
}

// GetOvertime mocks base method.
func (m *MockOvertimeRepositoryProvider) GetOvertime(ctx context.Context, userID, periodID int, date time.Time) (overtime.Overtime, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOvertime", ctx, userID, periodID, date)
	ret0, _ := ret[0].(overtime.Overtime)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOvertime indicates an expected call of GetOvertime.
func (mr *MockOvertimeRepositoryProviderMockRecorder) GetOvertime(ctx, userID, periodID, date interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOvertime", reflect.TypeOf((*MockOvertimeRepositoryProvider)(nil).GetOvertime), ctx, userID, periodID, date)
}

// InsertOvertime mocks base method.
func (m *MockOvertimeRepositoryProvider) InsertOvertime(ctx context.Context, ot overtime.Overtime) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertOvertime", ctx, ot)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertOvertime indicates an expected call of InsertOvertime.
func (mr *MockOvertimeRepositoryProviderMockRecorder) InsertOvertime(ctx, ot interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertOvertime", reflect.TypeOf((*MockOvertimeRepositoryProvider)(nil).InsertOvertime), ctx, ot)
}
